#
# Docker-compose file for running timeloop/accelergy
#
# Notes: 
#    The READMEs are put in ./workspace
#    The workspace will be owned by $USER_UID:$USER_GID
#

# Run as follows:
#
#    1) Put this file in an otherwise empty directory
#    2) Change USER_UID and USER_GID to the desired owner of your files (echo $UID )
#    3) Cd to the directory containing this file
#    4) Run the following command:
#
#        % If you are using x86 CPU (Intel, AMD)
#        % DOCKER_ARCH=amd64 docker-compose run infrastructure 
#
#        % If you are using arm CPU (Apple M1/M2)
#        % DOCKER_ARCH=arm64 docker-compose run infrastructure 
#
#        % If you want to avoid typing "DOCKER_ARCH=" every time,
#        % "export DOCKER_ARCH=<your architecture>" >> ~/.bashrc && source ~/.bashrc
#

version: '3'

services:
  infrastructure:
    hostname: accelergy-timeloop
    image: timeloopaccelergy/accelergy-timeloop-infrastructure:latest-${DOCKER_ARCH}
    volumes:
      - ./workspace:/home/workspace
    environment:
      - USER_UID=1000
      - USER_GID=1000
    stdin_open: true
    tty: true
