#
# Docker-compose file for running timeloop/accelergy
#
# Notes: 
#    The READMEs are put in ./workspace
#    The workspace will be owned by $USER_UID:$USER_GID
#

# Run as follows:
#
#    1) Put this file in an otherwise empty directory
#    2) Change USER_UID and USER_GID to the desired owner of your files (echo $UID )
#    3) Cd to the directory containing this file
#    4) Run the following command:
#
#        % docker-compose run infrastructure 
#    

version: '3'

services:
  infrastructure:
    hostname: accelergy-timeloop
    image: vi270662/accelergy-timeloop-infrastructure-with-mcpat:latest
    volumes:
      - ./workspace:/home/workspace
    environment:
      - USER_UID=1000
      - USER_GID=1000
    stdin_open: true
    tty: true
